import express from "express";

import {
    createConversation,
    getConversations,
    getConversation,
    updateConversation,
    addMessage,
    deleteMessage,
    deleteConversation,
    sendCoachMessage,
} from "../controllers/coachConversation.controller.js";

import authenticate from "../middlewares/auth.middleware.js";

const router = express.Router();

/**
 * @GET : /getAll-coach-conversation
 * @description :
 * Retrieves all AI Career Coach conversations belonging to
 * the authenticated user.
 * @access : Private
 */
router.get("/getAll-coach-conversation", authenticate, getConversations);

/**
 * @POST : /create-coach-conversation
 * @description :
 * Creates a new AI Career Coach conversation.
 * @access : Private
 */
router.post("/create-coach-conversation", authenticate, createConversation);

/**
 * @GET : /:conversationId
 * @description :
 * Retrieves a specific AI Career Coach conversation.
 * @access : Private
 */
router.get("/:conversationId", authenticate, getConversation);

/**
 * @PATCH : /:conversationId
 * @description :
 * Updates a specific AI Career Coach conversation.
 * @access : Private
 */
router.patch("/:conversationId", authenticate, updateConversation);

/**
 * @POST : /:conversationId/messages
 * @description :
 * Adds a new message to an existing AI Career Coach conversation.
 * @access : Private
 */
router.post("/:conversationId/messages", authenticate, addMessage);

/**
 * @DELETE : /:conversationId/messages/:messageId
 * @description :
 * Deletes a specific message from an AI Career Coach conversation.
 * @access : Private
 */
router.delete("/:conversationId/messages/:messageId", authenticate, deleteMessage);

/**
 * @DELETE : /:conversationId
 * @description :
 * Deletes a specific AI Career Coach conversation.
 * @access : Private
 */
router.delete("/:conversationId", authenticate, deleteConversation);

/**
 * @POST : /conversations/message
 * @description :
 * Send coach message generated by AI
 * @access : Private
 */
router.post("/conversations/message",authenticate,sendCoachMessage)

export default router;